version: '3.8'

services:
  backend:
    build: ./backend
    container_name: oasis-backend
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://oasis:oasis@db:5432/oasis
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8009:8000"
    depends_on:
      - db
      - redis
    networks:
      - oasis-network

  frontend:
    build: ./frontend
    container_name: oasis-frontend
    ports:
      - "3009:80"
    depends_on:
      - backend
    networks:
      - oasis-network

  db:
    image: pgvector/pgvector:pg15
    container_name: oasis-db
    environment:
      - POSTGRES_DB=oasis
      - POSTGRES_USER=oasis
      - POSTGRES_PASSWORD=oasis
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oasis-network

  redis:
    image: redis:7-alpine
    container_name: oasis-redis
    networks:
      - oasis-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  oasis-network:
    driver: bridge
