# Generated by Django 4.2.7 on 2025-09-14 20:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('custom_simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.customsimulation')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField()),
                ('strategic_score', models.IntegerField()),
                ('communication_score', models.IntegerField()),
                ('emotional_score', models.IntegerField()),
                ('strengths', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('improvements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('recommendations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('key_moments', models.JSONField(default=list)),
                ('tactics_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='simulations.simulation')),
            ],
            options={
                'db_table': 'simulation_analyses',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simulations.simulation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
