# Generated by Django 4.2.7 on 2025-09-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_message_action_items_message_business_impact_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='last_message_preview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulation',
            name='objectives_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='simulation',
            name='total_objectives',
            field=models.IntegerField(default=0),
        ),
    ]
