# Generated by Django 4.2.7 on 2025-09-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_simulation_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='last_message_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='objectives_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='total_objectives',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
