# Generated by Django 4.2.7 on 2025-09-14 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_simulations', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(max_length=100)),
                ('current_score', models.IntegerField(default=0)),
                ('target_score', models.IntegerField(default=85)),
                ('sessions_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_scores',
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
