# Generated by Django 4.2.7 on 2025-09-14 20:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('participants', models.CharField(max_length=200)),
                ('objectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('user_role', models.TextField()),
                ('ai_role', models.TextField()),
                ('ai_personality', models.JSONField(default=dict)),
                ('ai_objectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('user_objectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('end_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('knowledge_base', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
